theme: just-the-docs

title: Unofficial Unity Package Manager Registry

exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

aux_links:
  "Unofficial Unity Package Manager Registry on GitHub":
    - "//github.com/upm-packages/upm-packages"

plugins:
  - jekyll-seo-tag
